theme: jekyll-theme-cayman
title: 'UC Davis Bioinformatics Core July Alliance for Global Health Makerere University Workshop - Variant Analysis'
tagline: 'July 29 - August 9, 2019'
name: 'UC Davis Bioinformatics Core July Alliance for Global Health Makerere University Workshop - Variant Analysis'
github:
  repository_url: 2019-Alliance-for-Global-Health-and-Science-Makerere-University_Variants
